### ISSUE TITLE
Switching between different applications

### ISSUE THREAD

**Issue by vonMitzscha** [Johann150/neutron-electron#1]
Sometimes it happened that after writing in Neutron and then switching to an other program (e.g. Firefox) the picture on the board was deleted. But only **sometimes** not every time 😕

**Comment by Johann150** [comment]
This might be because Electron repaints the whole window when switching back to it.
The problem with this is that neutron does at the moment not notice this.

**Comment by Johann150** [comment]
Could probably be fixed in [BrowserWindow.focus](https://electronjs.org/docs/api/browser-window#event-focus) by calling `repaintAll();`
